export const state = {
  lastInterviewId: null,
  lastReportResult: null,
  currentQuestion: "",
  speechOn: false,
  isListening: false,
  micPermissionGranted: false,
  activeRecognition: null,
  voiceCommittedText: "",
  manualStopRequested: false,
  interviewStartTs: null,
  interviewTimerHandle: null,
  interviewLimitSec: 0,
  timingMode: "count",
  /** Timer warning banners (time-limited interviews). */
  timeWarningsEnabled: true,
  timeWarningThresholds: { "5min": 300, "2min": 120, "1min": 60, "30sec": 30 },
  timeWarningsTts: true,
  timeWarningsShown: null,
  aiHostSpeaking: false,
  micAlwaysOn: false,
  showSpokenText: false,
  /** True while End Interview / timer / completion is tearing down UI (May 2026). */
  endingInterview: false,
  redirecting: false,
  transcriptInitialized: false,
  /** Smart auto-advance (voice-driven flow). */
  autoAdvance: {
    enabled: false,
    initial_response_wait_sec: 5,
    silence_detection_sec: 3,
    no_response_countdown_sec: 3,
    auto_skip_enabled: true,
    voice_commands_enabled: true,
    confirmation_before_next_sec: 3,
    minimum_answer_words: 5,
    minimum_speech_duration_sec: 2,
    speech_energy_threshold: 0.038,
    speech_confirm_ms: 400,
  },
  currentQuestionIndex: 0,
  questionSource: "",
  isWarmupTurn: false,
};
